### ISSUE TITLE
knxtools usage

### ISSUE THREAD

**Issue by Race666** [calimero-project/calimero-tools#19]
Is it possible to show a more meaningful error message regarding the required arguments and formats?

```
docker run --rm -ti calimeroproject/knxtools write "2/0/15" 9.002 1 -m knxip 127.0.0.1
WARNING: Unknown module: io.calimero.serial.provider.rxtx specified to --add-reads
08:18:59.974 [ERROR  ] io.calimero.tools.ProcComm: completed with error
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.Main.newLink(Main.java:436)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.ProcComm.createLink(ProcComm.java:535)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.ProcComm.start(ProcComm.java:334)
        
```
        
```
docker run --rm -ti calimeroproject/knxtools write "2/0/15"  1 -m knxip 127.0.0.1
WARNING: Unknown module: io.calimero.serial.provider.rxtx specified to --add-reads
08:23:44.292 [ERROR  ] io.calimero.tools.ProcComm: completed with error
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.Main.newLink(Main.java:436)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.ProcComm.createLink(ProcComm.java:535)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.ProcComm.start(ProcComm.java:334)   
```     

No idea what's wrong here and which format was expected :-( This works in older versions (2.4)

**Comment by bmalinowsky** [comment]
Thanks for noticing, it was an internal error when casting the default number of reconnect attempts which are now configurable. Docker images will follow.
